const RolesPermisos = {
  gestorEditor: ["eliminarEditarEquipos", "crearEquipos"],
  gestorFacturacion: ["cuentaCombro", "cotizacion"],
  gestorIntegral: [
    "eliminarEditarEquipos",
    "crearEquipos",
    "cuentaCombro",
    "cotizacion",
  ],
  administrador: [
    "eliminarEditarEquipos",
    "crearEquipos",
    "eliminarUsuarios",
    "crearUsuarios",
    "cuentaCombro",
    "cotizacion",
  ],
};
export default RolesPermisos;

export const departamentosYMunicipios = {
  Atlántico: [
    "Barranquilla",
    "Baranoa",
    "Campo de la Cruz",
    "Candelaria",
    "Galapa",
    "Juan de Acosta",
    "Luruaco",
    "Malambo",
    "Manatí",
    "Palmar de Varela",
    "Piojó",
    "Polonuevo",
    "Ponedera",
    "Puerto Colombia",
    "Repelón",
    "Sabanagrande",
    "Sabanalarga",
    "Santa Lucía",
    "Santo Tomás",
    "Soledad",
    "Suan",
    "Tubará",
    "Usiacurí",
  ],
  Bolívar: [
    "CARTAGENA DE INDIAS",
    "MAGANGUÉ",
    "ARJONA",
    "TURBACO",
    "EL CARMEN DE BOLÍVAR",
    "MARÍA LA BAJA",
    "SANTA ROSA DEL SUR",
    "SANTA CRUZ DE MOMPOX",
    "SAN PABLO",
    "SAN JUAN NEPOMUCENO",
    "MAHATES",
    "SAN JACINTO",
    "PINILLOS",
    "CALAMAR",
    "SANTA ROSA DE LIMA",
    "TIQUISIO",
    "MONTECRISTO",
    "MORALES",
    "SAN MARTÍN DE LOBA",
    "BARRANCO DE LOBA",
    "SIMITÍ",
    "VILLANUEVA",
    "ACHÍ",
    "ARENAL",
    "REGIDOR",
    "SAN ESTANISLAO",
    "ALTOS DEL ROSARIO",
    "RÍO VIEJO",
    "BRAZUELO DE PAPAYAL",
    "SAN FERNANDO",
    "TURBANÁ",
    "SANTA CATALINA",
    "HATILLO DE LOBA",
    "CLEMENCIA",
    "CÓRDOBA",
    "ZAMBRANO",
    "TALAIGUA NUEVO",
    "CICUCO",
    "MARGARITA",
    "SAN JACINTO DEL CAUCA",
    "ARROYOHONDO",
    "CANTAGALLO",
    "SOPLAVIENTO",
    "EL PEÑÓN",
    "EL GUAMO",
    "SAN CRISTÓBAL",
    "NOROSÍ",
  ],
  Magdalena: [
    "Algarrobo",
    "Aracataca",
    "Ariguaní",
    "Cerro de San Antonio",
    "Chibolo",
    "Ciénaga",
    "Concordia",
    "El Banco",
    "El Piñón",
    "El Retén",
    "Fundación",
    "Guamal",
    "Nueva Granada",
    "Pedraza",
    "Pijiño del Carmen",
    "Pivijay",
    "Plato",
    "Pueblo Viejo",
    "Remolino",
    "Sabanas de San Ángel",
    "Salamina",
    "San Sebastián de Buenavista",
    "Santa Ana",
    "Santa Bárbara de Pinto",
    "Santa Marta",
    "San Zenón",
    "Sitionuevo",
    "Tenerife",
    "Zapayán",
    "Zona Bananera",
  ],
};
